SELECT 
TO_TIMESTAMP_TZ(TO_CHAR(CAST(sysdate AS TIMESTAMP WITH TIME ZONE), 'DD-MM-YY HH24:MI:SS TZH:TZM'), 'DD-MM-YY HH24:MI:SS TZH:TZM' )as aa,
TO_CHAR(CAST(sysdate AS TIMESTAMP WITH TIME ZONE), 'yyyy-MM-dd"T"HH24:MI:SSTZH:TZM') as bb
FROM dual;
