  CREATE OR REPLACE EDITIONABLE SYNONYM "XXPL_TEST"."XXFND_APPR_HIST_ID_S" FOR "XXFND"."XXFND_APPR_HIST_ID_S";



GRANT SELECT ON XXDYR.PERSON_STG TO XXDYR_SELF;
COMMIT;
CREATE SYNONYM XXDYR_SELF.PERSON_STG FOR XXDYR.PERSON_STG;

-- CREATE SYNONYM PER_ASSIGNMENT_STG FOR XXDYR.PER_ASSIGNMENT_STG;


-- GRANT SELECT ON XXDYR.PER_ASSIGNMENT_STG TO XXDYR_SELF;
-- GRANT SELECT ON XXDYR.EMP_DEPARTMENTS TO XXDYR_SELF;
-- GRANT SELECT ON XXDYR.GRADES TO XXDYR_SELF;
-- GRANT SELECT ON XXDYR.JOB TO XXDYR_SELF;
-- GRANT SELECT ON XXDYR.USERS_STG TO XXDYR_SELF;
-- GRANT SELECT ON XXDYR.absence TO XXDYR_SELF;
-- GRANT SELECT ON XXDYR.positions TO XXDYR_SELF;
-- GRANT SELECT ON XXDYR.Person_Loan TO XXDYR_SELF;
-- GRANT SELECT ON XXDYR.PERSON_LEAVE_BAL TO XXDYR_SELF;
