CREATE TABLE XXEPG_INT_PROCESS_REQUESTS(
 Interface_run_id		NUMBER	 GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY
,Interface_id			NUMBER	
,Interface_code			VARCHAR2(100)
,Interface_name			VARCHAR2(240)
,Interface_run_date		DATE	default sysdate not null
,Interface_run_by		VARCHAR2(240)
,Interface_Parameters	VARCHAR2(240)
,Interface_status		VARCHAR2(240)
,Interface_message		VARCHAR2(2000)
,OIC_REFERENCE			VARCHAR2(240)
,VBCS_CODE				VARCHAR2(240)
,Creation_date			DATE		 default sysdate not null
,Created_by				VARCHAR2(100)
,Last_update_date		DATE		 default sysdate not null
,Last_updated_by		VARCHAR2(100)
,Last_update_login		VARCHAR2(100)
);
