SELECT 
--* 
distinct POST_TYPE, PROCESS_ID
FROM XXPOS_CASH_BOX_TRANS_ALL 
WHERE 
INTERFACE_STATUS=:PINTERFACESTATUS
AND INTERFACE_MODULE=:PINTERMODULE
AND to_date(TRANS_DATE, 'DD-MON-YYYY') BETWEEN to_date(:PFROMDATE, 'DD-MON-YYYY') and to_date(:PTODATE, 'DD-MON-YYYY')
